vocab_config:
  vocab_path: vocab/vocab_krsp.txt

model_config:
  name: encoder
  embedding_dim: 512
  num_layers: 8
  num_heads: 8
  dff: 2048
  dropout: 0.1
  classes: 6

dataset_config:
  data_path: /home/xushuli/Downloads/kr/krpr
  corpus_name: krpr
  train_prefix: train
  dev_prefix: dev
  test_prefix: test
  quick_debug : false

optimizer_config:
  init_steps: 0
  warmup_steps: 2000
  max_lr: 5e-6
  beta1: 0.9
  beta2: 0.999
  epsilon: 1e-9

running_config:
  load_weights: false
  weights_path: ./saved_weights/kr_model
  use_multi_gpu : true
  run_eagerly : false
  batch_size: 100
  epochs: 400
  steps_per_epoch: 500
